### ISSUE TITLE
GetAddressByPaymentMethod location

### ISSUE THREAD

**Issue by pxjoachim** [PayEx/PayEx.Magento2#30]
Suggestion from customer:

All settings for PayEx the modules can be found under Stores > Configuration > Sales > Payment Methods > PayEx Payments.

Except for the option to deactivate GetAddressByPaymentMethod, which can be found under Stores > Configuration > PayEx > Social Security Number. It would be more intuitive if all module settings could be found on the same location.

**Comment by olegisk** [comment]
I do not think it's a good idea. Because "Stores > Configuration > Sales > Payment Methods" is place for payment method configuration. Meanwhile magento payment extensions allow extent magento features (in our case - SSN field for checkout). It's not payment feature.
Please note payex payment extension provide additional feature: payment fee and provide configuration in standard place, under Configuration->Sales->Tax. See screenshot.
![configuration - settings - stores - magento admin](https://user-images.githubusercontent.com/871275/31308124-b913a408-ab92-11e7-84d6-87cb0a2d2e5a.png)

**Comment by olegisk** [comment]
See https://github.com/PayEx/PayEx.Magento2/commit/9448058dd7cd924011d053ee4544388184272857
