### ISSUE TITLE
Payment methods not available on edit order/refund

### ISSUE THREAD

**Issue by vmalyk** [PayEx/PayEx.Magento2#36]
If you want edit order information you can`t copy payment information from original order or create order with payex methods

**Comment by aait** [comment]
It is possible to credit a captured order. You need to navigate to the invoice of the order and there create a credit memo. Please see screenshots: 
![1](https://cloud.githubusercontent.com/assets/6286270/25997025/76c9d730-371a-11e7-841a-a2b3f11c033d.png)
![1 1](https://cloud.githubusercontent.com/assets/6286270/25997028/7a625a52-371a-11e7-9569-c3fdbf1251ed.png)
![2](https://cloud.githubusercontent.com/assets/6286270/25997032/7cd2b28c-371a-11e7-8181-6df2be7f385d.png)

**Comment by vmalyk** [comment]
Payment information for order with Payex: http://prntscr.com/f6z89d
After click "Edit": http://prntscr.com/f6z9bn

**Comment by aait** [comment]
Please follow instructions. Edit button is not possible. Payment has already been processed and sent to PayEx.

**Comment by vmalyk** [comment]
In my case I have order without generated invoice. Order is placed in "on Hold" after "Processing" status. Invoice isn`t generated. So, credit memo doesn`t applicable  in this case.

**Comment by aait** [comment]
Amount is already authorized at PayEx and in customer account.  Therefore this is not possible. If you like you can in theory capture an amount less then the whole authorized amount when invoicing. In that case you need to cancel the remaining of the order so that the remaining doesnt stay stay reserved on customer account.
